(function(r,s){var A=s.documentElement,e=r.T,i=Object.prototype,B=i.toString,D=Array.prototype.slice;function m(a){return B.call(a)=="[object Array]"}function w(a){return B.call(a)=="[object Function]"}var J=i.hasOwnProperty,E="T.FVS";i=s.getElementsByTagName("script");function t(){var a=r.console,b=arguments;if(a&&a.log)a.log.apply?a.log.apply(a,b):a.log(D.call(b))}function x(a,b,d,c){d=new RegExp("(?:^|&)"+a+"=([^&]*)(?:&|$)","i");return(c=b.match(d))?c[1]:""}function y(){}function n(a,b){m(a)||
(a=[a]);for(b=0;b<a.length;b++)try{a[b]()}catch(d){t(d,a[b])}}var u=[],F={},K=0,L=0;function M(a,b,d,c,f){for(b=0;u[b];b++){d=1;c=u[b];m(c[0])||(c[0]=[c[0]]);for(f=0;c[0][f];f++)if(o[c[0][f]]===j)c[0].splice(f--,1);else{d=0;break}if(d||a&&!c[2]){n(c[1]);u.splice(b--,1)}}}function U(a,b,d){u.push([a,b,d]);M(g._);return e}i=i[i.length-1];var V=i.src.replace(/[^\/]+$/,"");i=i.getAttribute("data-cfg");var N=x("k",i),W=/:\[([^\]]+)\]@/,X=/^[^@]+@/,Y=/(?:4|d|te)$/,j=true;function z(a,b,d,c,f,k){f=D.call(arguments,
4);a=w(a)?a:y;b=b||8;k=function(){a.apply(c,f)};return d?r.setInterval(k,b):r.setTimeout(k,b)}function C(a,b,d){for(d in b)a[d]=b[d]}function O(a){w(a)&&n(a);return e}function g(a,b){b=this;b.k=a||[];b.z=g.i++;g.$[b.z]=b}function o(a,b,d,c,f,k){if(J.call(o,b))o[b]===j&&z(g.d,50,0,g);else{o[b]=y;K++;f=s.createElement("script");f.type="text/javascript";f.defer="defer";f.charset="UTF-8";f.id="r_s_k_"+g.i++;f.async=j;k=function(){if(Y.test(f.readyState)){clearInterval(B._);f.onerror=f.onload=null;A.removeChild(f);
z(d)}};if(f.readyState)B._=z(k,50,j);f.onerror=f.onload=k;if(c)f.text="try{("+a+'())}catch(e){}document.getElementById("'+f.id+'").onload()';else f.src=a;A.insertBefore(f,A.firstChild)}}function G(a,b){if(a==E)b={h:p._F};return b||p._V&&p._V[a]||{h:H}}function Z(a,b){b=G(a);if(p._I&&a!=E)a=a.replace(/\./g,"/");return(b.p||V)+p._M.replace(/#k/g,a).replace(/#v/g,b.h||H)}var p={},P=location.hostname,Q=(new Date).getTime(),H=Q.toString(32),h,l,q;if(e){if(m(e.$w)){u=u.concat(e.$w);delete e.$w}for(q in e)if(/^_[MIF]$/.test(q)){p[q]=
e[q];delete e[q]}q=e.cache}else{q=x("che",i)=="true";C(p,{_M:x("fmt",i)||"#k.js?v=#v",_I:x("sis",i)=="true",_F:x("cfv",i)||H});r.T=e={using:function(a,b){if(!e.$r)e.$r=[];e.$r.push([a,b]);return e},coreReady:function(a){if(!e.$c)e.$c=[];e.$c.push(a);return e},allReady:function(a){if(!e.$a)e.$a=[];e.$a.push(a);return e},publish:function(a){if(!e._L)e._L={};C(e._L,a);return e}}}C(g,{i:0,$:{},L:{},d:function(a,b,d,c){a=this;for(b in a.$)a.$[b].r();a._=c=K==L;M(c);if(c){e.allReady=O;if(e.$a){n(e.$a);
delete e.$a}}},n:function(a){z(function(){if(F[a]!==j){o[a]=j;F[a]=j;L++;w(e.onload)&&n(function(){e.onload(a,F)})}g.d(a)},50)},l:function(a,b,d,c,f,k,R){m(g.L[a])||(g.L[a]=[]);c=[];if(m(b)){d||(g.L[a]=g.L[a].concat(b));for(f=0;f<b.length;f++){k=b[f];if(k==a)c.push(a);else(R=g.l(a,g.L[k],j))&&c.push(k,R)}}return c.join(">")},prototype:{r:function(a,b,d){a=this;if(d=a.k.length)for(b=0;b<d;b++)if(o[a.k[b]]===j){d--;a.k.splice(b--,1)}if(!d){w(a.f)&&a.f();delete g.$[a.z]}},a:function(a){this.k.push(a)}}});
n(function(){s.domain=P;s.domain=P.split(".").slice(-2).join(".")});i={"0":{_:function(){return h=r.localStorage},get:function(a){return h.getItem(a)},set:function(a,b){h.setItem(a,b)},del:function(a){h.removeItem(a)}},"2":{_:function(){return h=r.globalStorage[s.domain]},get:function(a){return h.getItem(a).value},set:function(a,b){h.setItem(a,b)},del:function(a){h.removeItem(a)}},"1":{_:function(){h=A;h.addBehavior("#default#userdata");return j},get:function(a){h.load(a);return h.getAttribute(a)},
set:function(a,b){h.load(a);h.setAttribute(a,b);h.save(a)},del:function(a){h.load(a);h.expires=Q.toUTCString();h.save(a)}}};for(var I=0,S;I<3;I++){l=i[I];try{S=l._()}catch(ba){}if(S){delete l._;break}else l=0}l||(l={get:y,set:y,del:y});function T(a,b,d,c){c=J.call(t,a)&&t[a];if(!c){if((b=l.get(a))&&(new RegExp("^"+G(a).h+":")).test(b)){d=b.match(W);c={c:b.replace(X,""),d:d&&d[1].split(",")||[]}}t[a]=c}return c}function $(a,b,d,c){b=b.substring(b.lastIndexOf("/")+1);a.a(b);if(c=T(b)){d=function(){o(c.c,
b,function(){g.n(b)},j)};v(c.d,d)}else o(Z(b),b,function(){z(function(){t[b+"_"]||g.n(b)},50)})}function v(a,b,d,c){m(a)||(a=[a]);if(a.length){d=new g;d.f=function(){n(b)};for(c=0;c<a.length;c++)$(d,a[c])}else n(b)}function aa(){e.coreReady=O;if(e.$c){n(e.$c);delete e.$c}}C(e,{Store:l,observe:U,DOMAIN:s.domain,invoke:function(a,b,d,c){if(m(a)){for(b=0;b<a.length;b++)d=e.invoke(a[b]);return d}c=e._L;d=!j;if(c&&w(c[a]))d=c[a].apply(c,D.call(arguments,1));return d},isCached:function(a,b,d,c){if(b=T(a)){if(b.d&&
b.d.length)for(d=0;d<b.d.length;d++){c=e.isCached(b.d[d]);if(!c)return c}c=j}return c},cache:function(a,b,d,c){t[a+"_"]=j;m(b)||(b=[]);if(c=g.l(a,b))throw new Error(c+" @ "+a);v(b,function(){g.n(a);d();q&&l.set(a,G(a).h+":["+b+"]@"+d)})}});v(E,function(){p._V=e._V;v(N&&N.split(",")||[],aa);e.using=function(b,d){v(b,d);return e};if(e.$r){for(var a=0;a<e.$r.length;a++)v(e.$r[a][0],e.$r[a][1]);delete e.$r}})})(window,document);
